### ISSUE TITLE
Add a check in/out & register page

### ISSUE THREAD

**Issue by daonb** [cut-covid/cut-covid-www#1]
The new page should have a url as in `http://ochains.org/hub/<hub id>`. 

If the user already has an ID stored in local storage he will be shown a page with "checkin" & "checkout" buttons. Clicking the button will send a POST request to `cico.<our domain>.org` with:

- the user's public key
- the type of interaction: checkin or checkout
- last 3 digits of his ID (optional)
- for checkin: the estimated length of stay (optional)
- for checkout: the estimated time since checkin (optional, for those who forgot to checkin)

After pressing a button the user will get a thank you page.

If the user has no ID stored in his browser's localStorgae, he will be directed to a registration page where he will be requested to enter his phone number and last three number of his ID number. This information will be POSTed to `users.<our domain>.org` where a new key will be generated for the user and sent in the response. This key will be saved in local storage for future checkins.

**Comment by arthurgarmider** [comment]
I though that /hub/<hub id> - will be used for creation of new hubs and /hub/<hub id>/user/<user id>
will be used for user checkin & checkout

**Comment by daonb** [comment]
I thin they are separate servers: http://www.ochains.org/hub/<hub id> is what is encoded in the QR code and returns a web page. the 'www' will server html, css, media & js that will access the other servers, i.e. http://hubs.ochains.org/hub for hub CRUD operations, http://cico.ochians.org/cico for checkin/checkout posts, etc.
