### ISSUE TITLE
Register business/hub - add: "Internal Zones/positions list"

### ISSUE THREAD

**Issue by Yarons321** [cut-covid/cut-covid-www#18]
Register business/hub
UI
Hub details: 

- Business name, type, hub address
- company ID (osek mourshe) 
- contact person: 
- name, contact phone
- Internal Zones/positions list
- Zone type: 
-- Room/office/ designated area
-- Restaurant Table
-- Train couch
-- Customized hub info
-- Other: please elaborate ____
-- Zones unique numbers list
--- Total number of zones
--- Starts from 1, or enter other (value)

Add internally: 
Time & date, Hub UID (+hub CID)

**Comment by daonb** [comment]
@arthurgarmider how are we going to do it API wise? Maybe allow a dot in the hub's id so we'll have XY.Z where Z is the region?

**Comment by daonb** [comment]
Here's the API changed I've made:

```json
{
    "name":"Louna",
    ...
    "zoning":"rooms",
    "zones":["zone a","zone b","zone c"]
}
```
