### ISSUE TITLE
Design & Document the hubs server API

### ISSUE THREAD

**Issue by daonb** [cut-covid/cut-covid-www#2]

**Comment by arthurgarmider** [comment]
I suggest the following fields in the schema:
 id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(100), unique=True)
  type = db.Column(db.String(200))
  address = db.Column(db.String(200))
  contact_name = db.Column(db.String(200))
  contact_details = db.Column(db.String(200))
  company_id = db.Column(db.String(200))

and auto generated epoch_time

**Comment by daonb** [comment]
Looks good. What about the employees?

**Comment by arthurgarmider** [comment]
I think it is a property of a user

**Comment by daonb** [comment]
so the user should have a  field `empolyed_by` with a uri to a hub? what about those who work in more than one hub?

why do we need employees anyways?

**Comment by arthurgarmider** [comment]
Not sure we need to, I trust Yaron on this, but if we do, it should be a one to many table from the users table to the uid,hubid table

**Comment by daonb** [comment]
@Yarons321 we're not sure we need employees just now. what's missing from the normal user flow?
